import os

_TARGET_ENV = os.getenv("TARGET_ENV", "qa").lower()

_ENVIRONMENTS = {
    "dev": {
        "BASE_URL": "https://practicesoftwaretesting.com",
        "LOGIN_PATH": "/auth/login",
        "REGISTER_PATH": "/auth/register",
        "DASHBOARD_PATH": "/admin/dashboard",
        "PAGE_TITLE": "Login",
        "VALID_EMAIL": "admin@practicesoftwaretesting.com",
        "VALID_PASSWORD": "welcome01",
        "INVALID_EMAIL": "admine@practicesoftwaretesting.com",
        "INVALID_PASSWORD": "welcome02",
        "INVALID_LOGIN_MESSAGE": "Invalid email or password",
        "REGISTER_FIRST_NAME": "Test",
        "REGISTER_LAST_NAME": "User",
        "REGISTER_DATE_OF_BIRTH": "1980-12-12",
        "REGISTER_HOUSE_NUMBER": "123",
        "REGISTER_STREET": "Test Street",
        "REGISTER_POST_CODE": "10001",
        "REGISTER_CITY": "Sample City",
        "REGISTER_STATE": "Sample State",
        "REGISTER_COUNTRY": "Turkey",
        "REGISTER_PHONE": "5550000000",
        "REGISTER_PASSWORD": "Valid@123",
        "REGISTER_SHORT_PASSWORD": "12345",
        "REGISTER_PASSWORD_ERROR": "Password must be minimal 6 characters long.",
        "REGISTER_DUPLICATE_EMAIL_MESSAGE": "A customer with this email address already exists",
        "REGISTER_REQUIRED_FIRST_NAME": "First name is required",
        "REGISTER_REQUIRED_LAST_NAME": "Last name is required",
        "REGISTER_REQUIRED_DOB": "Date of Birth is required",
        "REGISTER_REQUIRED_HOUSE_NUMBER": "House number is required",
        "REGISTER_REQUIRED_STREET": "Street is required",
        "REGISTER_REQUIRED_POST_CODE": "Postcode is required",
        "REGISTER_REQUIRED_CITY": "City is required",
        "REGISTER_REQUIRED_STATE": "State is required",
        "REGISTER_REQUIRED_COUNTRY": "Country is required",
        "REGISTER_REQUIRED_PHONE": "Phone is required.",
        "REGISTER_REQUIRED_EMAIL": "Email is required",
        "REGISTER_REQUIRED_PASSWORD": "Password is required",
    },
    "qa": {
        "BASE_URL": "https://practicesoftwaretesting.com",
        "LOGIN_PATH": "/auth/login",
        "REGISTER_PATH": "/auth/register",
        "DASHBOARD_PATH": "/admin/dashboard",
        "PAGE_TITLE": "Login",
        "VALID_EMAIL": "admin@practicesoftwaretesting.com",
        "VALID_PASSWORD": "welcome01",
        "INVALID_EMAIL": "admine@practicesoftwaretesting.com",
        "INVALID_PASSWORD": "welcome02",
        "INVALID_LOGIN_MESSAGE": "Invalid email or password",
        "REGISTER_FIRST_NAME": "Test",
        "REGISTER_LAST_NAME": "User",
        "REGISTER_DATE_OF_BIRTH": "1980-12-12",
        "REGISTER_HOUSE_NUMBER": "123",
        "REGISTER_STREET": "Test Street",
        "REGISTER_POST_CODE": "10001",
        "REGISTER_CITY": "Sample City",
        "REGISTER_STATE": "Sample State",
        "REGISTER_COUNTRY": "Turkey",
        "REGISTER_PHONE": "5550000000",
        "REGISTER_PASSWORD": "Valid@123",
        "REGISTER_SHORT_PASSWORD": "12345",
        "REGISTER_PASSWORD_ERROR": "Password must be minimal 6 characters long.",
        "REGISTER_DUPLICATE_EMAIL_MESSAGE": "A customer with this email address already exists",
        "REGISTER_REQUIRED_FIRST_NAME": "First name is required",
        "REGISTER_REQUIRED_LAST_NAME": "Last name is required",
        "REGISTER_REQUIRED_DOB": "Date of Birth is required",
        "REGISTER_REQUIRED_HOUSE_NUMBER": "House number is required",
        "REGISTER_REQUIRED_STREET": "Street is required",
        "REGISTER_REQUIRED_POST_CODE": "Postcode is required",
        "REGISTER_REQUIRED_CITY": "City is required",
        "REGISTER_REQUIRED_STATE": "State is required",
        "REGISTER_REQUIRED_COUNTRY": "Country is required",
        "REGISTER_REQUIRED_PHONE": "Phone is required.",
        "REGISTER_REQUIRED_EMAIL": "Email is required",
        "REGISTER_REQUIRED_PASSWORD": "Password is required",
    },
    "staging": {
        "BASE_URL": "https://practicesoftwaretesting.com",
        "LOGIN_PATH": "/auth/login",
        "REGISTER_PATH": "/auth/register",
        "DASHBOARD_PATH": "/admin/dashboard",
        "PAGE_TITLE": "Login",
        "VALID_EMAIL": "admin@practicesoftwaretesting.com",
        "VALID_PASSWORD": "welcome01",
        "INVALID_EMAIL": "admine@practicesoftwaretesting.com",
        "INVALID_PASSWORD": "welcome02",
        "INVALID_LOGIN_MESSAGE": "Invalid email or password",
        "REGISTER_FIRST_NAME": "Test",
        "REGISTER_LAST_NAME": "User",
        "REGISTER_DATE_OF_BIRTH": "1980-12-12",
        "REGISTER_HOUSE_NUMBER": "123",
        "REGISTER_STREET": "Test Street",
        "REGISTER_POST_CODE": "10001",
        "REGISTER_CITY": "Sample City",
        "REGISTER_STATE": "Sample State",
        "REGISTER_COUNTRY": "Turkey",
        "REGISTER_PHONE": "5550000000",
        "REGISTER_PASSWORD": "Valid@123",
        "REGISTER_SHORT_PASSWORD": "12345",
        "REGISTER_PASSWORD_ERROR": "Password must be minimal 6 characters long.",
        "REGISTER_DUPLICATE_EMAIL_MESSAGE": "A customer with this email address already exists",
        "REGISTER_REQUIRED_FIRST_NAME": "First name is required",
        "REGISTER_REQUIRED_LAST_NAME": "Last name is required",
        "REGISTER_REQUIRED_DOB": "Date of Birth is required",
        "REGISTER_REQUIRED_HOUSE_NUMBER": "House number is required",
        "REGISTER_REQUIRED_STREET": "Street is required",
        "REGISTER_REQUIRED_POST_CODE": "Postcode is required",
        "REGISTER_REQUIRED_CITY": "City is required",
        "REGISTER_REQUIRED_STATE": "State is required",
        "REGISTER_REQUIRED_COUNTRY": "Country is required",
        "REGISTER_REQUIRED_PHONE": "Phone is required.",
        "REGISTER_REQUIRED_EMAIL": "Email is required",
        "REGISTER_REQUIRED_PASSWORD": "Password is required",
    },
}

globals().update(_ENVIRONMENTS.get(_TARGET_ENV, _ENVIRONMENTS["qa"]))
TARGET_ENV = _TARGET_ENV
